version: "3.3"

sevices:
    my_backend:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 3001:3001


    my_database:
        build:
            context: .
            dockerfile: Dockerfile.mongo
        ports:
            - 27017:27017
          