version: "3.7"

services: 
    my-backend:
        build: 
            context: .
            dockerfile: Dockerfile
        ports: 
            - 1000:3001

    my-database:
        build:
            context: .
            dockerfile: Dockerfile.mongo
        ports: 
            - 1001:27017