version: "3.3"

services:
    my_backend:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 4500:4500


    my_database:
        image: mongo:latest
        ports:
            - 27017:27017
          