version: "3.3"

sevices:
    my_backend:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 4500:4500


    my_database:
        build:
            context: .
            dockerfile: Dockerfile.mongo
        ports:
            - 27017:27017
          